### ISSUE TITLE
Bug: policy_assignments_to_add displayName is mandatory and overrides built-in value when not provided

### ISSUE THREAD

**Issue by OmnipotentOwl** [Azure/terraform-provider-alz#30]
## Summary
When providing parameter values in `policy_assignments_to_add` the policy that has its parameter values overridden also overwrites the displayName with a null or empty string when the displayName is not provided in the input variables. In the code line below there should have been an `IsKnown` used to determine if the caller intends to change the displayName by providing a valid string or is leaving it at the default value by passing in a null.

https://github.com/Azure/terraform-provider-alz/blob/11c1a3ee02dc4e1beadef15a3a89ca538e734b29/internal/provider/archetype_data_source.go#L690

**Comment by matt-FFFFFF** [comment]
Hi @OmnipotentOwl 

Thank you for raising this. It is indeed a bug and we will fix it.

**Comment by matt-FFFFFF** [comment]
Released in 0.6.1
