### ISSUE TITLE
bug? policy assignment getting invalid parameter logAnalytics_1

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-provider-alz#83]
I am unsure what is causing this after digging around in the code, so logging here to come back to later.

When the assignments for `Deploy-VMSS-Monitoring` and `Deploy-VM-Monitoring` are being created, they are getting an extra parameter called `logAnalytics_1` injected. This parameter is not in the policy assignment archetype, so it must be getting injected by the code, but unsure where.

Here is a segment from a plan:
![image](https://github.com/Azure/terraform-provider-alz/assets/1612200/3ae9856f-fd03-4e14-b754-d8b0c262a09b)

Here is what the assignment looks like in the lib folder:
![image](https://github.com/Azure/terraform-provider-alz/assets/1612200/027043de-9a65-478a-8e89-12222d305a27)

This is resulting in these errors:
![image](https://github.com/Azure/terraform-provider-alz/assets/1612200/925d0354-f86d-47f5-a448-705007de933b)

This parameter is not present in the default policy values:
![image](https://github.com/Azure/terraform-provider-alz/assets/1612200/55949650-bc92-43a5-b8d4-2c6378aed6f3)

Searching the code base for this parameter name is not yielding any results yet.

To reproduce, deploy the example here: https://github.com/Azure/alz-terraform-accelerator/tree/bug-fix-vnext/templates/complete_vnext

**Comment by jaredfholgate** [comment]
I found it here: https://github.com/Azure/alzlib/blob/c78b71d626727c9d39d111b83560372385015c3f/policyassignmentparametervalues.go#L54

**Comment by jaredfholgate** [comment]
@matt-FFFFFF Should this method check to see if the parameter exists in the assignment and update it if it does rather than inserting it if it doesn't exist? https://github.com/Azure/alzlib/blob/c78b71d626727c9d39d111b83560372385015c3f/policyassignmentparametervalues.go#L36

**Comment by matt-FFFFFF** [comment]
this is now implemented
